theme: jekyll-theme-architect
gitalk:
  enable: true    #是否开启评论
  clientID: 830173dc2bcaf7208616        #生成的clientID
  clientSecret: 87a9de06260b05d5b98424aff0232f156e3188fd    #生成的clientSecret
  repo: FrontierQ.github.io    #仓库名称
  owner: FrontierQ    #github用户名
  admin: FrontierQ	
  distractionFreeMode: true #是否启用阴影遮罩
