theme: jekyll-theme-architect
gitalk:
  enable: true    #是否开启评论
  clientID: 4935f01c2e2673e73315        #生成的clientID
  clientSecret: 70433cb3e6dcb3a41805b85a7ebe6d8c9ea528d2    #生成的clientSecret
  repo: FrontierQ.github.io    #仓库名称
  owner: FrontierQ    #github用户名
  admin: FrontierQ	
  distractionFreeMode: true #是否启用阴影遮罩
